const types = {
    GET_REPLAYS: 'GET_REPLAYS',
    GET_REPLAYS_COMPLETE: 'GET_REPLAYS_COMPLETE',
    DATE_REPLAYS: 'DATE_REPLAYS',
    GET_DETAILED_REPLAYS_COMPLETE: 'GET_DETAILED_REPLAYS_COMPLETE',
    GET_STATS: 'GET_STATS'
}

export default types